// Row format: [kanji or null (hiragana-only), kana, English]

const PEOPLE = [
  ['人', 'ひと', 'person'],
  ['男', 'おとこ', 'man'],
  ['女', 'おんな', 'woman'],
  ['子供', 'こども', 'child'],
  ['友達', 'ともだち', 'friend'],
  ['家族', 'かぞく', 'family'],
  ['父', 'ちち', '(my) father'],
  ['母', 'はは', '(my) mother'],
  ['兄', 'あに', '(my) older brother'],
  ['姉', 'あね', '(my) older sister'],
  ['弟', 'おとうと', 'younger brother'],
  ['妹', 'いもうと', 'younger sister'],
  ['両親', 'りょうしん', 'parents'],
  ['兄弟', 'きょうだい', 'siblings / brothers'],
  ['大人', 'おとな', 'adult'],
  ['彼', 'かれ', 'he / boyfriend'],
  ['彼女', 'かのじょ', 'she / girlfriend'],
  ['先生', 'せんせい', 'teacher'],
  ['学生', 'がくせい', 'student'],
  ['医者', 'いしゃ', 'doctor'],
  ['名前', 'なまえ', 'name'],
  ['今', 'いま', 'now'],
  ['今日', 'きょう', 'today'],
  ['明日', 'あした', 'tomorrow'],
  ['昨日', 'きのう', 'yesterday'],
  ['毎日', 'まいにち', 'every day'],
  ['朝', 'あさ', 'morning'],
  ['昼', 'ひる', 'noon / daytime'],
  ['夜', 'よる', 'night'],
  ['今朝', 'けさ', 'this morning'],
  ['今晩', 'こんばん', 'tonight / this evening'],
  ['週末', 'しゅうまつ', 'weekend'],
  ['来週', 'らいしゅう', 'next week'],
  ['先週', 'せんしゅう', 'last week'],
  ['今年', 'ことし', 'this year'],
  ['去年', 'きょねん', 'last year'],
  ['時間', 'じかん', 'time / hours'],
  ['年', 'とし', 'year / age'],
  ['月', 'つき', 'moon / month'],
  ['週', 'しゅう', 'week'],
  ['午前', 'ごぜん', 'a.m. / morning'],
  ['午後', 'ごご', 'p.m. / afternoon'],
  ['春', 'はる', 'spring'],
  ['夏', 'なつ', 'summer'],
  ['秋', 'あき', 'fall / autumn'],
  ['冬', 'ふゆ', 'winter'],
  ['誕生日', 'たんじょうび', 'birthday'],
  ['休み', 'やすみ', 'day off / break / vacation'],
  ['仕事', 'しごと', 'work / job'],
  ['会社', 'かいしゃ', 'company'],
];

const PLACES = [
  ['家', 'いえ', 'house / home'],
  ['部屋', 'へや', 'room'],
  ['学校', 'がっこう', 'school'],
  ['駅', 'えき', 'station'],
  ['店', 'みせ', 'store / shop'],
  ['病院', 'びょういん', 'hospital'],
  ['銀行', 'ぎんこう', 'bank'],
  ['図書館', 'としょかん', 'library'],
  ['郵便局', 'ゆうびんきょく', 'post office'],
  ['公園', 'こうえん', 'park'],
  ['道', 'みち', 'road / way'],
  ['町', 'まち', 'town'],
  ['国', 'くに', 'country'],
  ['空港', 'くうこう', 'airport'],
  ['台所', 'だいどころ', 'kitchen'],
  ['窓', 'まど', 'window'],
  ['机', 'つくえ', 'desk'],
  ['椅子', 'いす', 'chair'],
  ['電気', 'でんき', 'electricity / light'],
  ['電車', 'でんしゃ', 'train'],
  ['車', 'くるま', 'car'],
  ['自転車', 'じてんしゃ', 'bicycle'],
  ['地下鉄', 'ちかてつ', 'subway'],
  ['飛行機', 'ひこうき', 'airplane'],
  ['切符', 'きっぷ', 'ticket'],
  ['電話', 'でんわ', 'telephone'],
  ['時計', 'とけい', 'clock / watch'],
  ['傘', 'かさ', 'umbrella'],
  [null, 'かばん', 'bag'],
  ['財布', 'さいふ', 'wallet'],
  ['鍵', 'かぎ', 'key / lock'],
  ['靴', 'くつ', 'shoes'],
  ['服', 'ふく', 'clothes'],
  ['帽子', 'ぼうし', 'hat'],
  ['眼鏡', 'めがね', 'glasses'],
  ['本', 'ほん', 'book'],
  ['新聞', 'しんぶん', 'newspaper'],
  ['手紙', 'てがみ', 'letter'],
  ['写真', 'しゃしん', 'photo'],
  ['お金', 'おかね', 'money'],
  ['上', 'うえ', 'above / on top'],
  ['下', 'した', 'below / under'],
  ['前', 'まえ', 'front / before'],
  ['後ろ', 'うしろ', 'behind / back'],
  ['右', 'みぎ', 'right'],
  ['左', 'ひだり', 'left'],
  ['中', 'なか', 'inside'],
  ['外', 'そと', 'outside'],
  ['隣', 'となり', 'next to / next door'],
  ['近く', 'ちかく', 'nearby'],
];

const NATURE = [
  ['食べ物', 'たべもの', 'food'],
  ['飲み物', 'のみもの', 'drink'],
  ['ご飯', 'ごはん', 'cooked rice / meal'],
  ['朝ご飯', 'あさごはん', 'breakfast'],
  ['昼ご飯', 'ひるごはん', 'lunch'],
  ['晩ご飯', 'ばんごはん', 'dinner'],
  ['水', 'みず', 'water'],
  ['お茶', 'おちゃ', 'tea'],
  ['牛乳', 'ぎゅうにゅう', 'milk'],
  ['肉', 'にく', 'meat'],
  ['魚', 'さかな', 'fish'],
  ['野菜', 'やさい', 'vegetables'],
  ['果物', 'くだもの', 'fruit'],
  ['卵', 'たまご', 'egg'],
  ['塩', 'しお', 'salt'],
  ['砂糖', 'さとう', 'sugar'],
  ['お酒', 'おさけ', 'alcohol / sake'],
  ['料理', 'りょうり', 'cooking / dish'],
  ['味', 'あじ', 'taste / flavor'],
  ['体', 'からだ', 'body'],
  ['頭', 'あたま', 'head'],
  ['顔', 'かお', 'face'],
  ['目', 'め', 'eye'],
  ['耳', 'みみ', 'ear'],
  ['口', 'くち', 'mouth'],
  ['鼻', 'はな', 'nose'],
  ['歯', 'は', 'tooth'],
  ['手', 'て', 'hand'],
  ['足', 'あし', 'foot / leg'],
  ['声', 'こえ', 'voice'],
  ['病気', 'びょうき', 'illness / sick'],
  ['薬', 'くすり', 'medicine'],
  ['風邪', 'かぜ', 'a cold'],
  ['天気', 'てんき', 'weather'],
  ['雨', 'あめ', 'rain'],
  ['雪', 'ゆき', 'snow'],
  ['風', 'かぜ', 'wind'],
  ['空', 'そら', 'sky'],
  ['山', 'やま', 'mountain'],
  ['川', 'かわ', 'river'],
  ['海', 'うみ', 'sea / ocean'],
  ['花', 'はな', 'flower'],
  ['木', 'き', 'tree'],
  ['犬', 'いぬ', 'dog'],
  ['猫', 'ねこ', 'cat'],
  ['鳥', 'とり', 'bird'],
  ['動物', 'どうぶつ', 'animal'],
  ['火', 'ひ', 'fire'],
  ['星', 'ほし', 'star'],
  ['島', 'しま', 'island'],
];

const SCHOOL = [
  ['言葉', 'ことば', 'word / language'],
  ['日本語', 'にほんご', 'Japanese (language)'],
  ['英語', 'えいご', 'English (language)'],
  ['漢字', 'かんじ', 'kanji'],
  ['宿題', 'しゅくだい', 'homework'],
  ['試験', 'しけん', 'exam'],
  ['授業', 'じゅぎょう', 'class / lesson'],
  ['教室', 'きょうしつ', 'classroom'],
  ['質問', 'しつもん', 'question'],
  ['答え', 'こたえ', 'answer'],
  ['問題', 'もんだい', 'problem / question'],
  ['意味', 'いみ', 'meaning'],
  ['例', 'れい', 'example'],
  ['辞書', 'じしょ', 'dictionary'],
  ['教科書', 'きょうかしょ', 'textbook'],
  ['大学', 'だいがく', 'university'],
  ['高校', 'こうこう', 'high school'],
  ['趣味', 'しゅみ', 'hobby'],
  ['音楽', 'おんがく', 'music'],
  ['映画', 'えいが', 'movie'],
  ['歌', 'うた', 'song'],
  ['絵', 'え', 'picture / painting'],
  ['話', 'はなし', 'story / talk'],
  ['字', 'じ', 'character / handwriting'],
  ['色', 'いろ', 'color'],
  ['気持ち', 'きもち', 'feeling'],
  ['心', 'こころ', 'heart / mind'],
  ['考え', 'かんがえ', 'idea / thought'],
  ['理由', 'りゆう', 'reason'],
  ['約束', 'やくそく', 'promise / appointment'],
  ['予定', 'よてい', 'plan / schedule'],
  ['準備', 'じゅんび', 'preparation'],
  ['経験', 'けいけん', 'experience'],
  ['夢', 'ゆめ', 'dream'],
  ['世界', 'せかい', 'world'],
  ['社会', 'しゃかい', 'society'],
  ['文化', 'ぶんか', 'culture'],
  ['歴史', 'れきし', 'history'],
  ['地図', 'ちず', 'map'],
  ['用事', 'ようじ', 'errand / something to do'],
  ['番号', 'ばんごう', 'number'],
  ['住所', 'じゅうしょ', 'address'],
  ['会議', 'かいぎ', 'meeting'],
  ['給料', 'きゅうりょう', 'salary / pay'],
  ['値段', 'ねだん', 'price'],
  ['半分', 'はんぶん', 'half'],
  ['全部', 'ぜんぶ', 'all / everything'],
  ['最初', 'さいしょ', 'first / beginning'],
  ['最後', 'さいご', 'last / end'],
  ['次', 'つぎ', 'next'],
];

export const NOUN_DECKS = [
  { id: 'people', label: 'People & time', rows: PEOPLE },
  { id: 'places', label: 'Places & things', rows: PLACES },
  { id: 'nature', label: 'Food, body & nature', rows: NATURE },
  { id: 'school', label: 'School, work & ideas', rows: SCHOOL },
].map(({ id, label, rows }) => ({
  id,
  label,
  cards: rows.map(([kanji, kana, english], i) => ({
    id: `${id}-${i + 1}`,
    deck: id,
    kind: 'noun',
    kanji,
    kana,
    english,
  })),
}));

export const NOUNS = NOUN_DECKS.flatMap((d) => d.cards);
