// Row format: [kanji or null (hiragana-only), kana, polite form, English, conjugation type]

const CORE = [
  ['食べる', 'たべる', '食べます', 'to eat', 'ichidan'],
  ['飲む', 'のむ', '飲みます', 'to drink', 'godan'],
  ['行く', 'いく', '行きます', 'to go', 'godan'],
  ['来る', 'くる', '来ます（きます）', 'to come', 'irregular'],
  ['見る', 'みる', '見ます', 'to see / watch', 'ichidan'],
  ['聞く', 'きく', '聞きます', 'to hear / listen / ask', 'godan'],
  ['話す', 'はなす', '話します', 'to speak / talk', 'godan'],
  ['言う', 'いう', '言います', 'to say / tell', 'godan'],
  ['読む', 'よむ', '読みます', 'to read', 'godan'],
  ['書く', 'かく', '書きます', 'to write', 'godan'],
  ['買う', 'かう', '買います', 'to buy', 'godan'],
  ['売る', 'うる', '売ります', 'to sell', 'godan'],
  ['使う', 'つかう', '使います', 'to use', 'godan'],
  ['作る', 'つくる', '作ります', 'to make', 'godan'],
  [null, 'する', 'します', 'to do', 'irregular'],
  [null, 'ある', 'あります', 'to exist / have (inanimate)', 'godan'],
  [null, 'いる', 'います', 'to exist / be (living)', 'ichidan'],
  ['分かる', 'わかる', '分かります', 'to understand', 'godan'],
  ['思う', 'おもう', '思います', 'to think', 'godan'],
  ['知る', 'しる', '知ります', 'to know / find out', 'godan'],
  ['着る', 'きる', '着ます', 'to wear', 'ichidan'],
  ['分かれる', 'わかれる', '分かれます', 'to separate / split', 'ichidan'],
  ['帰る', 'かえる', '帰ります', 'to return / go home', 'godan'],
  ['入る', 'はいる', '入ります', 'to enter', 'godan'],
  ['出る', 'でる', '出ます', 'to leave / exit', 'ichidan'],
  ['開ける', 'あける', '開けます', 'to open', 'ichidan'],
  ['閉める', 'しめる', '閉めます', 'to close', 'ichidan'],
  ['起きる', 'おきる', '起きます', 'to wake up / get up', 'ichidan'],
  ['寝る', 'ねる', '寝ます', 'to sleep / go to bed', 'ichidan'],
  ['働く', 'はたらく', '働きます', 'to work', 'godan'],
  ['休む', 'やすむ', '休みます', 'to rest / take a break', 'godan'],
  ['会う', 'あう', '会います', 'to meet', 'godan'],
  ['待つ', 'まつ', '待ちます', 'to wait', 'godan'],
  ['持つ', 'もつ', '持ちます', 'to have / hold / carry', 'godan'],
  ['取る', 'とる', '取ります', 'to take', 'godan'],
  ['置く', 'おく', '置きます', 'to put / place', 'godan'],
  ['座る', 'すわる', '座ります', 'to sit', 'godan'],
  ['立つ', 'たつ', '立ちます', 'to stand', 'godan'],
  ['歩く', 'あるく', '歩きます', 'to walk', 'godan'],
  ['走る', 'はしる', '走ります', 'to run', 'godan'],
  ['洗う', 'あらう', '洗います', 'to wash', 'godan'],
  ['遊ぶ', 'あそぶ', '遊びます', 'to play / hang out', 'godan'],
  ['泳ぐ', 'およぐ', '泳ぎます', 'to swim', 'godan'],
  ['教える', 'おしえる', '教えます', 'to teach / tell', 'ichidan'],
  ['習う', 'ならう', '習います', 'to learn', 'godan'],
  ['忘れる', 'わすれる', '忘れます', 'to forget', 'ichidan'],
  ['覚える', 'おぼえる', '覚えます', 'to remember / memorize', 'ichidan'],
  ['始める', 'はじめる', '始めます', 'to start / begin', 'ichidan'],
  ['終わる', 'おわる', '終わります', 'to end / finish', 'godan'],
  ['乗る', 'のる', '乗ります', 'to ride / get on', 'godan'],
];

const DAILY = [
  ['降りる', 'おりる', '降ります', 'to get off (a train, bus)', 'ichidan'],
  ['電話する', 'でんわする', '電話します', 'to call (on the phone)', 'irregular'],
  ['勉強する', 'べんきょうする', '勉強します', 'to study', 'irregular'],
  ['料理する', 'りょうりする', '料理します', 'to cook', 'irregular'],
  ['掃除する', 'そうじする', '掃除します', 'to clean', 'irregular'],
  ['洗濯する', 'せんたくする', '洗濯します', 'to do laundry', 'irregular'],
  ['散歩する', 'さんぽする', '散歩します', 'to take a walk', 'irregular'],
  ['買い物する', 'かいものする', '買い物します', 'to go shopping', 'irregular'],
  ['浴びる', 'あびる', '浴びます', 'to take (a shower)', 'ichidan'],
  ['住む', 'すむ', '住みます', 'to live (somewhere)', 'godan'],
  ['着く', 'つく', '着きます', 'to arrive', 'godan'],
  ['出かける', 'でかける', '出かけます', 'to go out', 'ichidan'],
  ['戻る', 'もどる', '戻ります', 'to come back / go back', 'godan'],
  ['渡る', 'わたる', '渡ります', 'to cross (a street, bridge)', 'godan'],
  ['曲がる', 'まがる', '曲がります', 'to turn (left, right)', 'godan'],
  ['止まる', 'とまる', '止まります', 'to stop (by itself)', 'godan'],
  ['急ぐ', 'いそぐ', '急ぎます', 'to hurry', 'godan'],
  ['送る', 'おくる', '送ります', 'to send', 'godan'],
  ['借りる', 'かりる', '借ります', 'to borrow', 'ichidan'],
  ['貸す', 'かす', '貸します', 'to lend', 'godan'],
  ['返す', 'かえす', '返します', 'to give back / return (something)', 'godan'],
  [null, 'あげる', 'あげます', 'to give (to someone)', 'ichidan'],
  [null, 'もらう', 'もらいます', 'to receive', 'godan'],
  [null, 'くれる', 'くれます', 'to give (to me)', 'ichidan'],
  ['払う', 'はらう', '払います', 'to pay', 'godan'],
  ['呼ぶ', 'よぶ', '呼びます', 'to call (someone) / invite', 'godan'],
  ['手伝う', 'てつだう', '手伝います', 'to help (with a task)', 'godan'],
  ['撮る', 'とる', '撮ります', 'to take (a photo)', 'godan'],
  ['弾く', 'ひく', '弾きます', 'to play (an instrument)', 'godan'],
  ['歌う', 'うたう', '歌います', 'to sing', 'godan'],
  ['泣く', 'なく', '泣きます', 'to cry', 'godan'],
  ['笑う', 'わらう', '笑います', 'to laugh / smile', 'godan'],
  ['疲れる', 'つかれる', '疲れます', 'to get tired', 'ichidan'],
  ['始まる', 'はじまる', '始まります', 'to start (by itself)', 'godan'],
  ['開く', 'あく', '開きます', 'to open (by itself)', 'godan'],
  ['閉まる', 'しまる', '閉まります', 'to close (by itself)', 'godan'],
  [null, 'つける', 'つけます', 'to turn on (a light, TV)', 'ichidan'],
  ['消す', 'けす', '消します', 'to turn off / erase', 'godan'],
  ['押す', 'おす', '押します', 'to push / press', 'godan'],
  ['引く', 'ひく', '引きます', 'to pull', 'godan'],
  ['切る', 'きる', '切ります', 'to cut', 'godan'],
  ['入れる', 'いれる', '入れます', 'to put in', 'ichidan'],
  ['出す', 'だす', '出します', 'to take out / hand in', 'godan'],
  ['並ぶ', 'ならぶ', '並びます', 'to line up', 'godan'],
  ['見せる', 'みせる', '見せます', 'to show', 'ichidan'],
  ['探す', 'さがす', '探します', 'to look for', 'godan'],
  [null, 'できる', 'できます', 'to be able to / can do', 'ichidan'],
  [null, 'なる', 'なります', 'to become', 'godan'],
  ['降る', 'ふる', '降ります', 'to fall (rain, snow)', 'godan'],
  ['履く', 'はく', '履きます', 'to put on (shoes, pants)', 'godan'],
];

const TOWN = [
  ['脱ぐ', 'ぬぐ', '脱ぎます', 'to take off (clothes, shoes)', 'godan'],
  [null, 'かぶる', 'かぶります', 'to put on (a hat)', 'godan'],
  [null, 'かける', 'かけます', 'to hang / put on (glasses) / make (a call)', 'ichidan'],
  ['着替える', 'きがえる', '着替えます', 'to change clothes', 'ichidan'],
  ['磨く', 'みがく', '磨きます', 'to brush (teeth) / polish', 'godan'],
  ['起こす', 'おこす', '起こします', 'to wake (someone) up', 'godan'],
  ['片付ける', 'かたづける', '片付けます', 'to tidy up / put away', 'ichidan'],
  ['捨てる', 'すてる', '捨てます', 'to throw away', 'ichidan'],
  ['拾う', 'ひろう', '拾います', 'to pick up', 'godan'],
  ['落とす', 'おとす', '落とします', 'to drop (something)', 'godan'],
  ['落ちる', 'おちる', '落ちます', 'to fall / drop', 'ichidan'],
  ['壊れる', 'こわれる', '壊れます', 'to break (by itself)', 'ichidan'],
  ['壊す', 'こわす', '壊します', 'to break (something)', 'godan'],
  ['直す', 'なおす', '直します', 'to fix / repair', 'godan'],
  ['運ぶ', 'はこぶ', '運びます', 'to carry / transport', 'godan'],
  ['焼く', 'やく', '焼きます', 'to grill / bake', 'godan'],
  ['温める', 'あたためる', '温めます', 'to warm up / heat', 'ichidan'],
  ['集める', 'あつめる', '集めます', 'to collect / gather', 'ichidan'],
  ['吸う', 'すう', '吸います', 'to breathe in / smoke', 'godan'],
  ['触る', 'さわる', '触ります', 'to touch', 'godan'],
  ['動く', 'うごく', '動きます', 'to move / work (machine)', 'godan'],
  ['登る', 'のぼる', '登ります', 'to climb', 'godan'],
  ['飛ぶ', 'とぶ', '飛びます', 'to fly / jump', 'godan'],
  ['泊まる', 'とまる', '泊まります', 'to stay (overnight)', 'godan'],
  ['引っ越す', 'ひっこす', '引っ越します', 'to move (house)', 'godan'],
  ['通う', 'かよう', '通います', 'to go regularly / commute', 'godan'],
  ['通る', 'とおる', '通ります', 'to pass through / go by', 'godan'],
  ['向かう', 'むかう', '向かいます', 'to head toward', 'godan'],
  ['迎える', 'むかえる', '迎えます', 'to welcome / pick (someone) up', 'ichidan'],
  ['訪ねる', 'たずねる', '訪ねます', 'to visit', 'ichidan'],
  ['旅行する', 'りょこうする', '旅行します', 'to travel', 'irregular'],
  ['運転する', 'うんてんする', '運転します', 'to drive', 'irregular'],
  ['出発する', 'しゅっぱつする', '出発します', 'to depart', 'irregular'],
  ['遅れる', 'おくれる', '遅れます', 'to be late', 'ichidan'],
  ['間に合う', 'まにあう', '間に合います', 'to be in time / make it', 'godan'],
  ['見える', 'みえる', '見えます', 'to be visible / can see', 'ichidan'],
  ['聞こえる', 'きこえる', '聞こえます', 'to be audible / can hear', 'ichidan'],
  ['見つける', 'みつける', '見つけます', 'to find', 'ichidan'],
  ['見つかる', 'みつかる', '見つかります', 'to be found', 'godan'],
  [null, 'なくす', 'なくします', 'to lose (something)', 'godan'],
  ['足りる', 'たりる', '足ります', 'to be enough', 'ichidan'],
  ['要る', 'いる', '要ります', 'to need', 'godan'],
  ['違う', 'ちがう', '違います', 'to be different / wrong', 'godan'],
  ['晴れる', 'はれる', '晴れます', 'to clear up (weather)', 'ichidan'],
  ['吹く', 'ふく', '吹きます', 'to blow (wind)', 'godan'],
  ['咲く', 'さく', '咲きます', 'to bloom', 'godan'],
  ['残る', 'のこる', '残ります', 'to remain / be left over', 'godan'],
  ['残す', 'のこす', '残します', 'to leave (behind)', 'godan'],
  ['転ぶ', 'ころぶ', '転びます', 'to fall down / trip', 'godan'],
  ['怪我する', 'けがする', '怪我します', 'to get hurt', 'irregular'],
];

const MIND = [
  ['考える', 'かんがえる', '考えます', 'to think about / consider', 'ichidan'],
  ['信じる', 'しんじる', '信じます', 'to believe', 'ichidan'],
  ['感じる', 'かんじる', '感じます', 'to feel', 'ichidan'],
  ['決める', 'きめる', '決めます', 'to decide', 'ichidan'],
  ['決まる', 'きまる', '決まります', 'to be decided', 'godan'],
  ['選ぶ', 'えらぶ', '選びます', 'to choose', 'godan'],
  ['答える', 'こたえる', '答えます', 'to answer', 'ichidan'],
  ['調べる', 'しらべる', '調べます', 'to look up / check', 'ichidan'],
  ['比べる', 'くらべる', '比べます', 'to compare', 'ichidan'],
  ['数える', 'かぞえる', '数えます', 'to count', 'ichidan'],
  ['思い出す', 'おもいだす', '思い出します', 'to recall / remember', 'godan'],
  ['間違える', 'まちがえる', '間違えます', 'to make a mistake', 'ichidan'],
  ['質問する', 'しつもんする', '質問します', 'to ask a question', 'irregular'],
  ['説明する', 'せつめいする', '説明します', 'to explain', 'irregular'],
  ['練習する', 'れんしゅうする', '練習します', 'to practice', 'irregular'],
  ['復習する', 'ふくしゅうする', '復習します', 'to review (a lesson)', 'irregular'],
  ['頼む', 'たのむ', '頼みます', 'to ask (a favor) / order', 'godan'],
  ['約束する', 'やくそくする', '約束します', 'to promise', 'irregular'],
  ['招待する', 'しょうたいする', '招待します', 'to invite', 'irregular'],
  ['紹介する', 'しょうかいする', '紹介します', 'to introduce', 'irregular'],
  ['案内する', 'あんないする', '案内します', 'to guide / show around', 'irregular'],
  ['連絡する', 'れんらくする', '連絡します', 'to contact / get in touch', 'irregular'],
  ['心配する', 'しんぱいする', '心配します', 'to worry', 'irregular'],
  ['準備する', 'じゅんびする', '準備します', 'to prepare', 'irregular'],
  ['予約する', 'よやくする', '予約します', 'to reserve / book', 'irregular'],
  ['注文する', 'ちゅうもんする', '注文します', 'to order (food, items)', 'irregular'],
  ['伝える', 'つたえる', '伝えます', 'to tell / pass on (a message)', 'ichidan'],
  ['謝る', 'あやまる', '謝ります', 'to apologize', 'godan'],
  ['許す', 'ゆるす', '許します', 'to forgive / allow', 'godan'],
  ['断る', 'ことわる', '断ります', 'to refuse / turn down', 'godan'],
  ['助ける', 'たすける', '助けます', 'to help / save', 'ichidan'],
  ['守る', 'まもる', '守ります', 'to protect / keep (a promise)', 'godan'],
  ['勝つ', 'かつ', '勝ちます', 'to win', 'godan'],
  ['負ける', 'まける', '負けます', 'to lose (a game)', 'ichidan'],
  ['楽しむ', 'たのしむ', '楽しみます', 'to enjoy', 'godan'],
  ['喜ぶ', 'よろこぶ', '喜びます', 'to be happy / glad', 'godan'],
  ['驚く', 'おどろく', '驚きます', 'to be surprised', 'godan'],
  ['怒る', 'おこる', '怒ります', 'to get angry', 'godan'],
  ['困る', 'こまる', '困ります', 'to be in trouble / be stuck', 'godan'],
  ['慣れる', 'なれる', '慣れます', 'to get used to', 'ichidan'],
  ['頑張る', 'がんばる', '頑張ります', 'to do your best / hang in there', 'godan'],
  ['変える', 'かえる', '変えます', 'to change (something)', 'ichidan'],
  ['変わる', 'かわる', '変わります', 'to change (by itself)', 'godan'],
  ['増える', 'ふえる', '増えます', 'to increase', 'ichidan'],
  ['減る', 'へる', '減ります', 'to decrease', 'godan'],
  ['続ける', 'つづける', '続けます', 'to continue (something)', 'ichidan'],
  ['続く', 'つづく', '続きます', 'to continue (by itself)', 'godan'],
  ['生まれる', 'うまれる', '生まれます', 'to be born', 'ichidan'],
  ['結婚する', 'けっこんする', '結婚します', 'to get married', 'irregular'],
  ['卒業する', 'そつぎょうする', '卒業します', 'to graduate', 'irregular'],
];

export const VERB_DECKS = [
  { id: 'core', label: 'Core verbs', rows: CORE },
  { id: 'daily', label: 'Daily life', rows: DAILY },
  { id: 'town', label: 'Home, town & travel', rows: TOWN },
  { id: 'mind', label: 'Thoughts, feelings & people', rows: MIND },
].map(({ id, label, rows }) => ({
  id,
  label,
  cards: rows.map(([kanji, kana, polite, english, type], i) => ({
    id: `${id}-${i + 1}`,
    deck: id,
    kind: 'verb',
    kanji,
    kana,
    polite,
    english,
    type,
  })),
}));

export const VERBS = VERB_DECKS.flatMap((d) => d.cards);
